config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match 'signout',  :to => 'sessions#destroy'
  root :to => 'pages#home'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user
   
  validates :content, :presence => true, 
                  :length => { :maximum => 140 }
                  
  validates :user_id, :presence => true
  default_scope :order => 'microposts.created_at DESC'

end

app/models/user.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nom        :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :nom, :password, :password_confirmation
  
  has_many :microposts, :dependent => :destroy
  #créer des expréssions régulières http://www.rubular.com/
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :nom, :presence => true, 
                  :length => { :maximum => 50 }
  validates(:email, :presence => true, 
                    :format => {:with => email_regex},
                    :uniqueness => {:case_sensitive => false})
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }
                       
  before_save :encrypt_password
  
  def has_password?(password_soumis)
    encrypted_password == encrypt(password_soumis)
  end
  
  def self.authentificate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authentificate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    return nil  if user.nil?
    return user if user.salt == cookie_salt
  end
  
  def feed
    Micropost.where("user_id = ?", id)
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt (string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
  
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
# -*- encoding : utf-8 -*-
class MicropostsController < ApplicationController
  before_filter :authenticate, :only => [:create, :destroy]
  before_filter :authorized_user, :only => [:destroy]
  
  def create 
    @micropost = current_user.microposts.build(params[:micropost]) 
    if @micropost.save
      flash[:succes] = "Micropost a été crée!"
      redirect_to root_path
    else
      @feed_items = []
      render 'pages/home'
    end   
  end
  
  def destroy
    Micropost.find(params[:id]).destroy
    flash[:succes] = "Micropost supprimé" 
    redirect_to root_path
  end
  
  private
  
  def authorized_user
    @micropost = Micropost.find(params[:id])
    redirect_to root_path unless current_user?(@micropost.user)
  end  
  
  
end

app/controllers/pages_controller.rb
# -*- encoding : utf-8 -*-
class PagesController < ApplicationController
  def home
    @titre = "Accueil"
    if signed_in?
      @micropost = Micropost.new
      @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  
  end

  def contact
    @titre = "Contact"
  end
  
  def about
    @titre = "A Propos"
  end
  
  def help
    @titre = "Aide"
  end
end

app/controllers/sessions_controller.rb
# -*- encoding : utf-8 -*-
class SessionsController < ApplicationController
  def new
    @titre = "S'identifier"
  end
  
  def create
    user = User.authentificate(params[:session][:email],
                               params[:session][:password])
    if user.nil?
      flash.now[:error] = "Combinaison e-mail/mot de passe invalide"
      @titre = "S'identifier"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-

class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
    @titre = "Liste des utilisateurs"
    #@users = User.all
    @users = User.paginate(:page => params[:page])
  end
  
  def new
    @titre = 'Inscription'
    @user = User.new
  end
  
   def show
    @user = User.find_by_id(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @titre = @user.nom
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Bienvenue"+ @user.nom
      redirect_to @user
    else
      @titre = "Inscription"
      render 'new'
    end
  end
  
  def edit
   # @user = User.find(params[:id])
    @titre = "Édition profil"
  end
  
  def update 
   # @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profil actualisé"
      redirect_to @user
    else
      @titre = "Édition profil"
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find_by_id(params[:id])
    if !current_user?(@user)
      @user.destroy
      flash[:success] = "Utilisateur supprimé" + @user.nom
    else
      flash[:error] = "L'administrateur "+@user.nom+" ne peux être supprimé."
    end
    
    redirect_to users_path
  end
  
private
  
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
  #Retourner un titre basé sur la page
  def titre
    base_titre = "Simple App du Tutoriel Ruby on Rails"
    if @titre.nil?
      base_titre
    else
      "#{base_titre}|#{@titre}"
    end
  end
  
  def logo
   logo_titre = image_tag("logo.png", :alt => "Application exemple", :class => "round")
  end
end

app/helpers/pages_helper.rb
# -*- encoding : utf-8 -*-
module PagesHelper
end

app/helpers/sessions_helper.rb
# -*- encoding : utf-8 -*-
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
     @current_user ||= user_from_remember_token
  end
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def authenticate 
    dany_access unless signed_in?
  end
  
  def dany_access
    store_location
    redirect_to signin_path, :notice => "Merci de vous identifier pour rejoindre cette page."
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  def current_user?(user)
    user == current_user
  end
  
  private
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  def clear_return_to
    session[:return_to] = nil
  end
  
  def user_from_remember_token
    User.authentificate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
  
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
  
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.nom,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
  
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "A Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!--<% logo = image_tag("logo.png", :alt => "Application exemple", :class => "round") %>-->
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Accueil", root_path %></li>
      <% if signed_in? %>
	    <li><%= link_to "Utilisateurs", users_path %></li>
	 	<li><%= link_to "Profil", user_path(current_user) %></li>
	    <li><%= link_to "Réglages", edit_user_path(current_user) %></li>
      <% end %>
      	<li><%= link_to "Aide", help_path%></li>
      <%if signed_in?%>
      	<li><%= link_to "Deconnexion",signout_path, :method => :delete%></li>
      <%else%>
      	<li><%= link_to "Connexion",signin_path%></li>
      <%end%>
      
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @titre %></title>
    <%= csrf_meta_tag %>
   	<%= render 'layouts/stylesheets' %>
   	<%= javascript_include_tag "application" %>
  </head>
  <body>
     <div class="container">
      <header>
        <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
        <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posté il y a <%= time_ago_in_words(micropost.created_at) %>.
    </span>
</tr>

app/views/pages/about.html.erb
    <h1>About us</h1>
    <p>
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  est un projet de livre et de screencasts pour apprendre le développement web
  avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. C'est l'Application Exemple de ce tutoriel.
    </p>

app/views/pages/contact.html.erb
    <h1>Contact</h1>
    <p>
      Contact du Tutoriel Ruby on Rails à propos de l'Application Exemple à la
  <a href="http://railstutorial.org/feedback">page de feedback</a>.
    </p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette Application Exemple, voyez le 
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
    <% if signed_in? %>
    
	    <table class="front" summary="Pour visiteur identifié">
	    	<tr>
	    		<td class="main">
	    			<h1 class="micropost">Quoi de neuf ?</h1>
	    			<%= render 'shared/micropost_form' %>
	    			<%= render 'shared/feed'%>
	    		</td>
	    		
	    		<td class="sidebar round">
	    			<%= render 'shared/user_info' %>
	    		</td>
	    	</tr>
	    </table>
	    
    <% else%>
    
    <h1>Application exemple</h1>
    <p>
      Ceci est la page d'accueil de l'Application Exemple du
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>.
    </p>
    
	<%= link_to "S'inscrire !", signup_path, :class => "signup_button round" %>
	
	<%end%>
    

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
    	<%= pluralize(object.errors.count, "erreur") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
    	from being saved:
    </h2>
    <p>Merci de corriger ces champs :</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="microposts" summary="User microposts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to feed_item.user.nom, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posté il y a <%= time_ago_in_words(feed_item.created_at) %>.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
  <td>
    <%= link_to "supprimer", feed_item, :method => :delete,
                                     :confirm => "Etes-vous certain ?",
                                     :title => feed_item.content %>
  </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Soumettre" %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.nom %>
    </span>
    <span class="microposts">
     <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.label :nom %><br />
  <%= f.text_field :nom %>
</div>

<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>

<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>

<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_user.html.erb
<li>
  	<%= gravatar_for user, :size => 30 %>
  	<%= link_to user.nom, user %>
	<% if current_user.admin? %>
<!--
	Solution pour le problème de rediredirection directement sur le show!
	voir application.html
	#http://stackoverflow.com/questions/8726534/rails-3-1-link-to-not-showing-confirmation-or-destroying-properly-->
  		<%= link_to " supprimer", user, :method => :delete,:confirm => "Etes-vous certain?", :title => "Supprimer #{user.nom}" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<h1>Edition du profil</h1>

<%= form_for(@user) do |f| %>
	<%= render 'fields', :f => f %>
	
	<div class="actions">
		<%=f.submit "Update"%>
	</div>
	
	<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails" target="_blank">changer</a>
</div>
<% end %>

app/views/users/index.html.erb
<h1>Tous les utilisateurs</h1>
<%= will_paginate %>
	<ul class="users">
		<%= render @users %>
	</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>Inscription</h1>

<%= form_for(@user) do |f| %>
	
	<%= render 'fields', :f => f %>
	<div class="actions">
		<%=f.submit "Inscription"%>
	</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Information du profil">
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.nom %>
			</h1>
			<% unless @user.microposts.empty? %>
				<table class="micropost" summary="Micro-message de l'utilisateur">
					<%= render @microposts%>
				</table>
				<%= will_paginate @microposts%>
			<% end %>
		</td>	
		<td class="sidebar round">
      		<strong>Nom</strong> <%= @user.nom %><br />
      		<strong>Email</strong> <%= @user.email %><br />
      		<strong>Path</strong>  <%= link_to user_path(@user), @user %><br/>
      		<strong>URL</strong>  <%= link_to user_url(@user), @user %><br/>
    		<strong>Message(s): </strong> <%= @user.microposts.count%>
    	</td>
	</tr>
</table>

<!--<%= @user.nom %>, <%= @user.email %>-->